### ISSUE TITLE
When will you release the code of 'Action Step Localization' and 'Action Segmentation' tasks?

### ISSUE THREAD

**Issue by butterluo** [microsoft/UniVL#3]
When will you release the code of 'Action Step Localization' and 'Action Segmentation' tasks?

**Comment by ArrowLuo** [comment]
We have no plan to release the 'Action Step Localization,' 'Action Segmentation,' and the 'Multimodal Sentiment Analysis' recently due to the extra clean job and checks. And may not be open source those parts in the future. If you have any questions on the details of implementation ignored in our paper, you can write to us via email or this issue.
